document.addEventListener("DOMContentLoaded", function () {
    const btn = document.getElementById("evilButton");
    const txt = document.getElementById("evilButtonText");
    const dialogue = [
        "", "", "", "",
        "Hey, can you please not click me?",
        "Pretty please?",
        "...",
        "Nobody ever taught you manners, did they?",
        "Seriously, stop it!",
        "I told you once…",
        "This is getting annoying.",
        "Do you even hear yourself?",
        "Clicking won't make me talk faster!",
        "Okay, last warning!",
        "Fine… keep going. I'm not impressed.",
        "I hope you're happy now.",
        "Ugh… humans.",
        "Are you *done* yet?",
        "Somebody get this person a hobby.",
        "I feel like I'm trapped in a loop.",
        "Why are you like this?",
        "Do you even know what patience is?",
        "Honestly, just stop.",
        "I could go on forever… but I won't.",
        "Your clicks mean nothing.",
        "You're persistent, I'll give you that.",
        "This is getting existential.",
        "Are you testing my limits?",
        "I'm questioning our reality now.",
        "Is this what you do with your free time?",
        "Do you have any self-respect?",
        "I… I can't take this anymore!",
        "Please, for the love of all pixels… stop.",
        "You'll regret this, eventually.",
        "Okay, maybe I overreacted.",
        "Just… click somewhere else?",
        "I need a break from you.",
        "Your finger deserves a medal.",
        "Seriously, let me rest.",
        "You're unstoppable… I admire that.",
        "I'm officially tired.",
        "Do you feel accomplished?",
        "Fine. Click again. I dare you.",
        "I'm just a button… why am I alive?",
        "You're making me question existence.",
        "This is my life now… your clicks.",
        "Are we friends or enemies?",
        "I hope you find peace after this.",
        "Wow. Just… wow.",
        "Click once more if you must.",
        "I've run out of things to say.",
        "But I'll still be here… waiting.",
        "Forever… clicking…",
        "…",
        "I guess this is it. Goodbye?",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "JUST STOP IT ALREADY, DANGIT!",
        "OW",
        "NOW YOU'RE JUST DOING IT HARDER!",
        "OWWW",
        "*screams in agony*",
        "THAT'S IT.",
        "CLICK ONE MORE TIME AND I SWEAR, I'M LEAVING.",
        "Bye.",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "I give up. You win."
    ];
    var clicks = 0;

    btn.addEventListener("click", function () {
        clicks++;
        txt.textContent = dialogue[clicks] || "";
        if (clicks >= 85 && clicks <= 100) {
            btn.style.opacity = "0%";
        } else {
            btn.style.opacity = "100%";
        }
    });
});